import os
import platform
import pathlib

system = platform.system()
system = system.lower()

sources = Glob("*.cc")
sources.append(["#/src/Neuron.cc",
                "#/src/Map.cc",
                "#/src/Perlin.cc",
                "#/src/CreatureFactory.cc",
                "#/src/RgbHsv.cc"])

if system == "windows":
    print("Windows!")
    env = Environment()

    env.Append(CPPPATH=['#include',
                        '#lib/SFML-2.5.1-Win/include',
                        '#lib/webview',
                        '#lib/boost_1_75_0',
                        pathlib.Path(os.__file__).parents[1] / 'include' 
                        ])

    env.Append(LINKFLAGS='/SUBSYSTEM:CONSOLE')

    env.Append(CXXFLAGS='/EHsc /MD /std:c++17 /openmp:experimental /O2')

    env.Append(LIBPATH=['#lib/SFML-2.5.1-Win/lib',
                        '#lib/webview/lib',
                        '#lib/boost_1_75_0/stage/lib',
                        pathlib.Path(os.__file__).parents[1] / 'libs'
                        ])

    env.Append(LIBS=['sfml-graphics',
                     'sfml-window',
                     'sfml-system',
                     'webview',
                     'WebView2Loader.dll'
                     ])

    env.Program('../bin/Tests', sources)

else:
    print("Linux!")
    env = Environment()
    env.Append(CPPDEFINES=['LINUX_PRAGMA'])
    env.Append(CPPPATH=['#include',
                        '#lib/webview',
                        '#lib/boost'])
    env.Append(CXXFLAGS='-std=c++17 -DWEBVIEWGTK -Wall -Wextra -fopenmp')
    env.ParseConfig('pkg-config --cflags --libs python3 gtk+-3.0 webkit2gtk-4.0')
    boost_json = File('#lib/boost/stage/lib/libboost_json.a')
    boost_filesystem = File('#lib/boost/stage/lib/libboost_filesystem.a')
    env.Append(CXXFLAGS='-Wall -std=c++17 -DWEBVIEWGTK')
    env.Append(LIBS=['sfml-graphics',
                     'sfml-window',
                     'sfml-system',
                     'gomp', boost_json, boost_filesystem, 'python3.8','-ldl'
                     ])
    env.Append(LIBPATH=['#/lib/boost/stage/lib'])
    VariantDir('#/build', '#/tests', duplicate=0)
    env.Program('../bin/Tests', sources)
