import os
import platform

system = platform.system()
system = system.lower()

env = Environment(CPPPATH = ['#include','#lib/boost_1_75_0',])

if system=="windows":
    print("windows")
    env.Append(LINKFLAGS='/SUBSYSTEM:CONSOLE')
    env.Append(CXXFLAGS=' /EHsc /MD /std:c++17 /openmp')
    env.Append(LIBS=['Shell32'])
else:
    print("linux")
    env.Append(CXXFLAGS='-Wall -std=c++17')
sources=Glob("*.cc")
sources.append(["#/src/Neuron.cc",
                "#/src/Map.cc",
                "#/src/Perlin.cc",
                "#/src/CreatureFactory.cc"])
env.Program('../bin/Tests',sources,LIBPATH=['#/lib/boost_1_75_0/stage/lib'])